version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/backend/app/index
      - ./backend:/app:rw
    environment:
      - PYTHONUNBUFFERED=1
      - LLM_DEVICE=cpu
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  backend_data:
    name: law_app_backend_index

